baseURL = 'https://wish-i-was-an-artist.netlify.app/'
languageCode = 'fr-fr'
title = 'Galerie'

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2


[taxonomies]
  category = 'categories'